#!/bin/bash
# Copyright (C) 2018 Mandy Wilkens

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

POWER_MANAGEMENT=$(iwconfig $(INTERFACE) | grep "Power Management" | awk '{ split($2,r,":"); print r[2]; }')

#------------------------------------------------------------------------

echo $POWER_MANAGEMENT # Display PM

# color
if [[ $POWER_MANAGEMENT -eq "off" ]]; then
    echo "#00FF00"
elif [[ $POWER_MANAGEMENT -eq "on" ]]; then
    echo "#FFAE00"
else
    echo "#FF0000"
fi
